#!/usr/bin/env bash

HOSTNAME=`hostname -s`

# The directory containing the xpm icons.
ICONS="$HOME/.xmonad/icons"

# DZEN
DZEN_BG="#111111"
DZEN_BAR_BG="gray40"
DZEN_BAR_FG="white"
DZEN_HEIGHT=25

# SCREENS
INTERNAL="eDP1"
EXTERNAL="DP2"

# Load host specific config.
hostconf="$HOME/.dotfiles/config.$HOSTNAME"
if [ -f $hostconf ]; then
   . $hostconf
fi
