#!/usr/bin/env bash

# Load the configuration.
. $(dirname $(readlink -f ${BASH_SOURCE[0]}))/../config

function current_time () {
    echo -n `date +"%a, %d %b %H:%M:%S"`
}

function kernel_release () {
    echo -n `uname -r`
}

function mpd_status_playing () {
    PLAYING=`! mpc | grep 'playing'`
    echo -n "$?"
}

function mpd_progress () {
    POS=`mpc | sed -ne 's/^.*(\([0-9]*\)%).*$/\1/p'`
    if [ $POS != "0" ]; then
        echo -n "$POS 100" | gdbar -h 8 -w 60 -fg '$DZEN_BAR_FG' -bg '$DZEN_BAR_BG' -s o
    fi
}

function mpd_title () {
    echo -n "`mpc | head -n 1`"
}

function mpd_volume () {
    echo -n "`mpc | grep volume | sed 's/volume: \([0-9]*\).*/\1/'`"
}
function mpd_progress_percentage () {
    PERCENT=`mpc | grep playing | sed 's/.*(\(.*\)%).*/\1/'`
    if [ $PERCENT != "0" ]; then
        echo " $PERCENT%% "
    fi
}

function volume_muted () {
    echo -n "`amixer | grep -A 6 \'$MIXER\'| awk {'print $6'} | grep -m 1 "[on|off]" | sed -e 's/[][]//g'`"
}

function volume () {

    ismute=`amixer |grep -A 6 \'$MIXER\'|awk {'print $7'} |grep -m 1 "[on|off]" | sed -e 's/[][]//g'`

    if [[ $ismute == "off" ]]; then
        echo -n "$(echo "0" | gdbar -ss 1 -sw 2 -fg '$DZEN_BAR_FG' -bg '$DZEN_BAR_BG' -h 7 -w 60)"
    else
        echo -n "`echo $(mpd_volume) | gdbar -ss 1 -sw 2 -fg \"$DZEN_BAR_FG\" -bg \"$DZEN_BAR_BG\" -h 7 -w 60`"
    fi

}

function pacman () {
    if [ `wc -l < $PACMAN_UPDATES` == "0" ]; then
        echo -n "pacman up to date"
    else
        echo -n "pacman needs more fruit"
    fi
}
