#!/usr/bin/env bash

# Load the dzen2 functions.
. $(dirname $(readlink -f ${BASH_SOURCE[0]}))/functions

DZEN_X=0
DZEN_Y=0

dzen2 -ta 'l' -h $DZEN_HEIGHT -fn 'Terminus-8' -x $DZEN_X -y $DZEN_Y -bg $DZEN_BG
