#!/usr/bin/env bash

# Load the dzen2 functions.
. $(dirname $(readlink -f ${BASH_SOURCE[0]}))/functions

DZEN_WIDTH=800

DZEN_X=$(expr $SCREEN_WIDTH - $DZEN_WIDTH)
DZEN_Y=0

cd ~ && conky -c ~/.xmonad/conky/top-right | dzen2 -x $DZEN_X -y $DZEN_Y -h $DZEN_HEIGHT -w $DZEN_WIDTH -ta r -bg $DZEN_BG
