#!/usr/bin/env bash

# Load the dzen2 functions.
. ~/.dotfiles/functions

SCREEN_WIDTH=$(screen_width)
SCREEN_HEIGHT=$(screen_height)

DZEN_X=0
DZEN_Y=$(expr $SCREEN_HEIGHT - $DZEN_HEIGHT)

while true ; do
    if [[ $(mpd_status_playing) == 1 ]]; then
        printf "^i($ICONS/music.xpm)$(mpd_progress_percentage)$(mpd_progress) $(mpd_title)\n"
    else
        printf "^i($ICONS/arch.xpm) $(uname -r)  ^ca(1,urxvt -e '$HOME/.xmonad/pacman/upgrade-system')^i($ICONS/pacman.xpm) $(pacman_status)^ca()\n"
    fi
    sleep 1
done | dzen2 -ta c -x $DZEN_X -y $DZEN_Y -h $DZEN_HEIGHT -w $SCREEN_WIDTH -bg $DZEN_BG
