#!/usr/bin/env bash

. ~/.dotfiles/functions

SCREEN_WIDTH=$(screen_width)
SCREEN_HEIGHT=$(screen_height)

while true ; do
    if [[ $(mpd_status_playing) == 1 ]]; then
        printf "^i($ICONS/music.xpm)$(mpd_progress_percentage)$(mpd_progress) $(mpd_title)\n"
    else
        printf "^i($ICONS/arch.xpm) $(uname -r)  ^ca(1,urxvt -e '$HOME/.xmonad/pacman/upgrade-system')^i($ICONS/pacman.xpm) $(pacman_status)^ca()\n"
    fi
    sleep 1
done | dzen2 -dock -ta c -y $(expr $SCREEN_HEIGHT - $DZEN_HEIGHT) -h $DZEN_HEIGHT -w $SCREEN_WIDTH
